/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Semana03;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author chris
 */
public class ejer01 extends javax.swing.JFrame {

    /**
     * Creates new form ejer01
     */
    public ejer01() {
        initComponents();
        btn_promedio.setToolTipText("Haz clic para calcular el promedio");
        setSize(450, 300);
        setResizable(false);
        setLocationRelativeTo(null);
        //JFrame.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_promedio = new javax.swing.JButton();
        lb_numero01 = new javax.swing.JLabel();
        lb_numero02 = new javax.swing.JLabel();
        lb_numero03 = new javax.swing.JLabel();
        lb_respuesta = new javax.swing.JLabel();
        tbn_limpiar = new javax.swing.JButton();
        txt_num01 = new javax.swing.JTextField();
        txt_num02 = new javax.swing.JTextField();
        txt_num03 = new javax.swing.JTextField();
        btn_salir = new javax.swing.JButton();
        lb_promedio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_promedio.setText("Promediar");
        btn_promedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_promedioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(281, 41, 90, -1));

        lb_numero01.setText("Numero01:");
        getContentPane().add(lb_numero01, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 28, -1, -1));

        lb_numero02.setText("Numero02:");
        getContentPane().add(lb_numero02, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 62, -1, -1));

        lb_numero03.setText("Numero03:");
        getContentPane().add(lb_numero03, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 96, -1, -1));

        lb_respuesta.setText("0.0");
        getContentPane().add(lb_respuesta, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        tbn_limpiar.setText("Limpiar");
        tbn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbn_limpiarActionPerformed(evt);
            }
        });
        getContentPane().add(tbn_limpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 90, -1));
        getContentPane().add(txt_num01, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 110, -1));
        getContentPane().add(txt_num02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 110, -1));
        getContentPane().add(txt_num03, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 110, -1));

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 90, -1));

        lb_promedio.setText("Promedio:");
        getContentPane().add(lb_promedio, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_promedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_promedioActionPerformed
        // TODO add your handling code here:
        float num1,num2,num3, prom;
        num1=Float.parseFloat(txt_num01.getText());
        num2=Float.parseFloat(txt_num02.getText());
        num3=Float.parseFloat(txt_num03.getText());
        prom=(num1+num2+num3)/3;
        lb_respuesta.setText(String.valueOf(prom));
    }//GEN-LAST:event_btn_promedioActionPerformed

    private void tbn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbn_limpiarActionPerformed
        // TODO add your handling code here:
        txt_num01.setText("");
        txt_num02.setText("");
        txt_num03.setText("");
        lb_respuesta.setText("0.0");
        txt_num01.requestFocus();
    }//GEN-LAST:event_tbn_limpiarActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Hasta pronto");
        System.exit(0);
        
    }//GEN-LAST:event_btn_salirActionPerformed
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ejer01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ejer01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ejer01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ejer01.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ejer01().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_promedio;
    private javax.swing.JButton btn_salir;
    private javax.swing.JLabel lb_numero01;
    private javax.swing.JLabel lb_numero02;
    private javax.swing.JLabel lb_numero03;
    private javax.swing.JLabel lb_promedio;
    private javax.swing.JLabel lb_respuesta;
    private javax.swing.JButton tbn_limpiar;
    private javax.swing.JTextField txt_num01;
    private javax.swing.JTextField txt_num02;
    private javax.swing.JTextField txt_num03;
    // End of variables declaration//GEN-END:variables
}
